import random
from words_list import Words

HangmanStages = ['''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
      |
      |
      |
=========
''', '''
  +---+
  |   |
      |
      |
      |
      |
=========
''']

print("Hangman Problem.")

#random word generated by the program
random_word = random.choice(Words)
word_length = len(random_word)
end_of_game = False

#Track the number of lives
numberoflives = 6


#Add "_" in an empty list
display = []

for _ in range(word_length):
    display += "_"




while not end_of_game:
    #Ask the user to enter a letter
    userinput = input("Guess the letter: ").lower()

    for position in range(word_length):
        letter = random_word[position]
        if letter == userinput:
            display[position] = letter

    if userinput not in random_word:
        numberoflives -=1
        if numberoflives == 0:
            end_of_game = True
            print("You lose")

    print(display)

    if "_" not in display:
        end_of_game = True
        print("You win")


    print(HangmanStages[numberoflives])